date = ['date', 'publishdate', 'pubdate', 'published', 'lastmod', 'modified', ':fileModTime']
lastmod = [':git', 'lastmod', 'modified', "fileModTime", 'date', 'publishdate', 'pubdate', 'published']

publishDate = ['publishdate', 'pubdate', 'published', 'date']
expiryDate = ["expiryDate"]
