date = ['date', 'publishdate', 'pubdate', 'published', 'lastmod', 'modified',':git',":filename",':fileModTime']
lastmod = [':git', ":fileModTime", 'lastmod', 'modified', 'date', 'publishdate', 'pubdate', 'published']
