#date = ['date', 'publishdate', 'pubdate', 'published', 'lastmod', 'modified',':git',":filename",':fileModTime']
#lastmod = [':git', ":fileModTime", 'lastmod', 'modified', 'date', 'publishdate', 'pubdate', 'published']

date = ['date', 'publishdate', 'pubdate', 'published', 'lastmod', 'modified']
expiryDate = ['expirydate', 'unpublishdate']
lastmod = [':git', 'lastmod', 'modified', 'date', 'publishdate', 'pubdate', 'published']
publishDate = ['publishdate', 'pubdate', 'published', 'date']
