date = [':fileModTime', ":filename",'date', 'publishdate', 'pubdate', 'published', 'lastmod', 'modified']
lastmod = [':git', ":fileModTime", 'lastmod', 'modified', 'date', 'publishdate', 'pubdate', 'published']

publishDate = ['publishdate', 'pubdate', 'published', 'date']
expiryDate = ["expiryDate"]
