disableCSS = false
disableHTML = false
disableJS = false
disableJSON = false
disableSVG = false
disableXML = false
minifyOutput = false

[tdewolff.css]
inline = false
keepCSS2 = true
precision = 0

[tdewolff.html]
keepComments = false
keepConditionalComments = false
keepDefaultAttrVals = true
keepDocumentTags = true
keepEndTags = true
keepQuotes = false
keepSpecialComments = true
keepWhitespace = false
templateDelims = [ "", "" ]

[tdewolff.js]
keepVarNames = false
precision = 0
version = 2_022

[tdewolff.json]
keepNumbers = false
precision = 0

[tdewolff.svg]
inline = false
keepComments = false
precision = 0

[tdewolff.xml]
keepWhitespace = false
