when:
  branch:
    exclude: pages

clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      recursive: true

steps:
  build:
    image: klakegg/hugo:ext
    commands:
      - npm install postcss postcss-cli @fullhuman/postcss-purgecss --save
      - HUGO_ENVIRONMENT=production; hugo --minify --gc --environment production
    when:
      event: [push, tag, cron, pull_request]
      branch: main

  deploy:
    image: alpine
    secrets: [deploy_key, known_hosts]
    commands:
      - apk --update add --no-cache hugo openssh-client rsync
      - mkdir /root/.ssh
      - chmod 700 /root/.ssh
      - echo "$DEPLOY_KEY">$HOME/.ssh/id_ed25519
      - chown 600 $HOME/.ssh/id_ed25519
      - ssh-keyscan -p 22 -H www.zyria.de > $HOME/.ssh/known_hosts
      - rsync -rPvc --delete -e "ssh -6" public/ fabrice@www.zyria.de:/srv/zyria_de
    when:
      status: success
      branch:
        include: [main]
      event: [push, deployment]
