when:
  branch:
    exclude: pages

clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      recursive: true

steps:
  build:
    image: klakegg/hugo:ext
    commands:
      - npm install postcss postcss-cli @fullhuman/postcss-purgecss --save
      - HUGO_ENVIRONMENT=production; hugo --minify --gc --environment production
    when:
      event: [push, tag, cron, pull_request]
      branch: main

  deploy:
    image: alpine
    secrets: [deploy_key, known_hosts, mail]
    environment:
      - HUGO_OUTPUT: public
    commands:
      - apk --update add --no-cache hugo git openssh-client
      - mkdir /root/.ssh
      - chmod 700 /root/.ssh
      - echo "$DEPLOY_KEY">$HOME/.ssh/id_ed25519
      - chown 600 $HOME/.ssh/id_ed25519
      - ssh-keyscan -p 2022 -H git.zyria.de > ~/.ssh/known_hosts
      - git config --global user.email $MAIL
      - git config --global user.name "Woodpecker CI"
      - git clone ssh://git@git.zyria.de:2022/pyrox/zyria_de-html.git $CI_REPO_NAME
      - rm -rf ./$CI_REPO_NAME/*
      # Copy build step output to repository folder
      - cp -ar $HUGO_OUTPUT/. $CI_REPO_NAME/
      # Commit and push all static files with pipeline started timestamp
      - cd $CI_REPO_NAME
      - git add .
      - git commit -m "Woodpecker CI ${CI_BUILD_CREATED}"
      - git push
    when:
      status: success
      branch:
        include: [main]
      event: [push, tag, cron, pull_request]

        #  deploy:
        #    image: alpine
        #    secrets: [deploy_key, known_hosts]
        #    commands:
        #      - apk --update add --no-cache openssh-client rsync
        #      - mkdir /root/.ssh
        #      - chmod 700 /root/.ssh
        #      - echo "$DEPLOY_KEY"> /root/.ssh/id_ed25519
        #      - chown 600 /root/.ssh/id_ed25519
        #      - rsync -rPvc --delete -e "ssh -6 -o StrictHostKeyChecking=accept-new" public/ fabrice@www.zyria.de:/srv/zyria_de
        #    when:
        #      status: success
        #      branch:
        #        include: [main]
        #      event: [push, tag, cron]
