---
name: Publish Site

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: https://git.zyria.de/pyrox/actions/hugo@10ba92a09f1d5efd9fe1b7e17dfdceb5ed936519 # v1.0
        with:
          ZYRIA_TOKEN: ${{ secrets.ZYRIA_TOKEN }}
