---
name: Mirror to Codeberg

on:
  push:
    branches:
      - main
      - master
  delete:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror
        uses: https://git.zyria.de/pyrox/actions/mirror@v1.0
        with:
          target_repo_url: 'git@codeberg.org:ricariel/${{ github.event.repository.name }}.git'
          ssh_private_key: ${{ secrets.ZYRIA_CODEBERG_SSH }}
