---
name: Mirror

on:
  push:
    branches:
      - main
      - master

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror
        uses: https://git.zyria.de/pyrox/actions/mirror@5f00b220bfac7c802703fea31da70df00b2b507e # v1
        with:
          target_repo_url: git@github.com:ricariel/${{ github.event.repository.name }}.git
          ssh_private_key: ${{ secrets.ZYRIA_GITHUB_SSH }}
