---
name: Mirror

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
      - master
  delete:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror
        uses: https://git.zyria.de/pyrox/actions/mirror@a269dd68a82414587c9c81a4ae9a015c60dc2154 # v1
        with:
          target_repo_url: git@github.com:ricariel/${{ github.event.repository.name }}.git
          ssh_private_key: ${{ secrets.ZYRIA_GITHUB_SSH }}
