---
name: Mirror

on:
  push:
    branches:
      - main
      - master

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror
        uses: https://git.zyria.de/pyrox/actions/mirror@10ba92a09f1d5efd9fe1b7e17dfdceb5ed936519 # v1.0
        with:
          target_repo_url: git@github.com:ricariel/${{ github.event.repository.name }}.git
          ssh_private_key: ${{ secrets.ZYRIA_GITHUB_SSH }}
