---

name: Pre-Commit Checks

on:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: https://code.forgejo.org/actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - uses: https://code.forgejo.org/actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6
      - name: Install detect-secret
        run: pip install detect-secrets
      - uses: https://github.com/pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
