---
name: Pre-Commit Checks

# yamllint disable-line rule:truthy
on:
  push:
    branches: [main]

jobs:
  call-reusable:
    runs-on: ubuntu-latest
    steps:
      - uses: https://git.zyria.de/pyrox/actions/pre-commit@a269dd68a82414587c9c81a4ae9a015c60dc2154 # v1
