---
name: renovate
on:
  schedule:
    - cron: '12 */6 * * *'
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Run renovate
        uses: https://git.zyria.de/pyrox/actions/renovate@10ba92a09f1d5efd9fe1b7e17dfdceb5ed936519 # v1.0
        with:
          gh-token: ${{ secrets.GITHUB }}
          token: ${{ secrets.RENOVATE_TOKEN }}
