---
name: renovate
on:
  schedule:
    - cron: '12 6 * * *'
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Run renovate
        uses: https://git.zyria.de/pyrox/actions/renovate@a38344044e10f21e926de8211be061f5e384db4d # v1
        with:
          gh-token: ${{ secrets.GITHUB }}
          token: ${{ secrets.RENOVATE_TOKEN }}
